swagger: '2.0'
info:
  title: Audio Mastery API
  version: 1.0.0
  description: Audio Mastery API definition
host: 'localhost:3000'
schemes:
  - http
externalDocs:
  description: Swagger spec v2 docs
  url: 'https://swagger.io/specification/v2/'
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  bearer:
    type: apiKey
    in: header
    name: Authorization
tags:
  - name: info
    description: API info
  - name: auth
    description: Authentication
  - name: users
    description: Users management
  - name: audios
    description: Audios management
paths:
  /info:
    get:
      operationId: getInfo
      description: Get API info
      tags:
        - info
      responses:
        '200':
          description: Ok
          schema:
            type: object
            properties:
              title:
                type: string
              version:
                type: string
              description:
                type: string
  /v1/login:
    post:
      operationId: postLogin
      description: User login
      tags:
        - auth
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
                format: email
              password:
                type: string
                minLength: 8
      responses:
        '200':
          description: Ok
          schema:
            type: object
            required:
              - token
            properties:
              token:
                type: string
        '400':
          description: Bad Request
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
  /v1/logout:
    get:
      operationId: getLogout
      description: User logout
      tags:
        - auth
      security:
        - bearer: []
      responses:
        '204':
          description: No Content
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
  /v1/users:
    post:
      operationId: postUser
      description: Creates a user
      tags:
        - users
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
                format: email
              password:
                type: string
                minLength: 8
      responses:
        '201':
          description: Created
          schema:
            type: object
            properties:
              id:
                type: string
                format: uuid
              email:
                type: string
                format: email
              createdAt:
                type: string
                format: date-time
              updatedAt:
                type: string
                format: date-time
        '400':
          description: Bad Request
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
  /v1/audio:
    get:
      operationId: listAudios
      description: Fetch audios
      tags:
        - audios
      security:
        - bearer: []
      responses:
        '200':
          description: Ok
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                user:
                  type: string
                  format: uuid
                record:
                  type: array
                  items:
                    type: string
                    format: byte
                createdAt:
                  type: string
                  format: date-time
                updatedAt:
                  type: string
                  format: date-time
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
    post:
      operationId: postAudio
      description: Creates an audio
      tags:
        - audios
      security:
        - bearer: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - record
            properties:
              record:
                type: array
                items:
                  type: string
                  format: byte
      responses:
        '204':
          description: No Content
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
        '401':
          description: Unauthorized
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
  '/v1/audio/{uuid}':
    get:
      operationId: getAudio
      description: Fetch a single audio
      tags:
        - audios
      security:
        - bearer: []
      parameters:
        - in: path
          name: uuid
          required: true
          type: string
      responses:
        '200':
          description: Ok
          schema:
            type: object
            properties:
              id:
                type: string
                format: uuid
              user:
                type: string
                format: uuid
              record:
                type: array
                items:
                  type: string
                  format: byte
              createdAt:
                type: string
                format: date-time
              updatedAt:
                type: string
                format: date-time
        '400':
          description: Bad Request
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
    put:
      operationId: putAudio
      description: Updates an audio
      tags:
        - audios
      security:
        - bearer: []
      parameters:
        - in: path
          name: uuid
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              record:
                type: array
                items:
                  type: string
                  format: byte
      responses:
        '204':
          description: No Content
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
        '400':
          description: Bad Request
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
        '401':
          description: Unauthorized
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
    delete:
      operationId: deleteAudio
      description: Deletes an audio
      tags:
        - audios
      security:
        - bearer: []
      parameters:
        - in: path
          name: uuid
          required: true
          type: string
      responses:
        '204':
          description: No Content
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
        '400':
          description: Bad Request
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
        '401':
          description: Unauthorized
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
        '500':
          description: Internal Server Error
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              status:
                type: string
              message:
                type: string
definitions:
  error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      status:
        type: string
      message:
        type: string
