swagger: "2.0"
info:
  title: Audio Mastery API
  version: 1.0.0
  description: Audio Mastery API definition

host: "localhost:3000"

schemes:
  - "http"

externalDocs:
  description: Swagger spec v2 docs
  url: https://swagger.io/specification/v2/

consumes:
  - application/json

produces:
  - application/json

securityDefinitions:
  bearer:
    type: apiKey
    in: header
    name: Authorization

tags:
  - name: info
    description: API info
  - name: auth
    description: Authentication
  - name: users
    description: Users management
  - name: audios
    description: Audios management

paths:
  /info:
    $ref: './paths/info/info.yaml'
  /v1/login:
    $ref: './paths/auth/auth.yaml#/login'
  /v1/logout:
    $ref: './paths/auth/auth.yaml#/logout'
  /v1/users:
    $ref: './paths/users/users.yaml'
  /v1/audio:
    $ref: './paths/audio/audio.yaml'
  /v1/audio/{uuid}:
    $ref: './paths/audio/audio_uuid.yaml'

definitions:
  user:
    $ref: "./definitions/user.yaml"
  audio:
    $ref: "./definitions/audio.yaml"
  error:
    $ref: "./definitions/error.yaml"
